"use client";

import Image from "next/image";
import { Download, HelpCircle, LogOut, MessageSquarePlus, Settings } from "lucide-react";
import type { DemoUser } from "@/lib/local-platform-service";
import type { ProcessedRecord } from "@/lib/announcement-data";
import { exportCsv, formatDate } from "@/lib/announcement-data";

export function CozeHeader({ user, baseline, brokerCount, data, onDefinition, onFeedback, onAdmin, onLogout }: { user: DemoUser; baseline: Date | null; brokerCount: number; data: ProcessedRecord[]; onDefinition: () => void; onFeedback: () => void; onAdmin: () => void; onLogout: () => void }) {
  return <header className="sticky top-0 z-30 flex min-w-0 flex-col overflow-hidden border-b border-blue-500/20 bg-[#102847] px-3 py-3 text-white sm:flex-row sm:items-center sm:px-8"><div className="flex min-w-0 flex-1 items-center gap-2"><Image src="/brand/company-icon.png" alt="世纪证券" width={36} height={36} className="rounded-lg" /><div><h1 className="text-[15px] font-bold sm:text-[18px]">世纪证券招采情报平台</h1><p className="hidden text-[11px] text-[#B7C6D9] sm:block">对公展示版 · 洞察招采趋势 · 追踪供应商动态</p></div></div><div className="mt-2 flex min-w-0 items-center gap-1.5 text-[11px] text-slate-300 sm:mt-0 sm:gap-3 sm:text-[12px]"><span className="hidden md:inline">最新数据：<b className="text-white">{formatDate(baseline)}</b> · 覆盖主体：<b className="text-white">{brokerCount}</b></span><button onClick={onDefinition} className="inline-flex items-center gap-1 rounded-lg border border-white/15 px-2.5 py-1.5 hover:bg-white/10"><HelpCircle className="h-3.5 w-3.5" />口径</button><button onClick={onFeedback} className="inline-flex items-center gap-1 rounded-lg border border-sky-300/40 px-2.5 py-1.5 text-sky-100 hover:bg-sky-400/20"><MessageSquarePlus className="h-3.5 w-3.5" />反馈</button><button onClick={() => exportCsv(data)} className="inline-flex items-center gap-1 rounded-lg bg-blue-600 px-2.5 py-1.5 font-semibold hover:bg-blue-500"><Download className="h-3.5 w-3.5" />导出</button>{user.isAdmin && <button onClick={onAdmin} className="inline-flex items-center gap-1 rounded-lg border border-amber-400/40 px-2.5 py-1.5 text-amber-300 hover:bg-amber-400/10"><Settings className="h-3.5 w-3.5" />管理</button>}<span className="hidden max-w-20 truncate sm:inline">{user.name || user.username}</span><button onClick={onLogout} className="rounded p-1.5 hover:bg-white/10" title="退出登录"><LogOut className="h-4 w-4" /></button></div></header>;
}
